#!/usr/bin/env python3
"""Generate monochrome weather icon bitmaps for the display.

Source art is https://github.com/metno/weathericons, whose PNGs are coloured
with transparency. The shape lives in the alpha channel, not in luminance:
clearsky_day's darkest pixel is only 164, so thresholding on brightness would
render it blank. Everything here silhouettes on alpha instead.

Sizes and naming follow https://github.com/engvik/met-bitmap-icons, which is
where the display's existing 50x50 set comes from and where these should
eventually be upstreamed. That repository's sets were made with image2cpp; the
settings below reproduce them to within about 0.3% of pixels, the difference
being edge antialiasing.

The device never runs this. Headers are generated once and committed.

    python3 tools/genicons.py
"""

import csv
import io
import json
import os
import urllib.request

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".icons")
OUT = os.path.abspath(os.path.join(HERE, "..", "src", "icons"))

LISTING = "https://api.github.com/repos/metno/weathericons/contents/weather/png"
RAW = "https://raw.githubusercontent.com/metno/weathericons/main/weather/png"
LICENCE_URL = "https://raw.githubusercontent.com/metno/weathericons/main/LICENSE"
LICENCE_FILE = "LICENSE-weathericons.txt"

# Condition names, keyed by the symbol code without its day/night variant.
LEGEND = "https://raw.githubusercontent.com/metno/weathericons/main/weather/legend.csv"

# MET publishes English, Bokmal and Nynorsk. The design captions in English.
LABEL_COLUMN = "English"

VARIANTS = ("day", "night", "polartwilight")

# The hourly strip and the weather hero. The display draws black on white, so
# the white variant met-bitmap-icons also carries is not generated here.
SIZES = [24, 44]

# Matched empirically against the image2cpp sets in met-bitmap-icons.
RESAMPLE = Image.BILINEAR
ALPHA_CUT = 64

BYTES_PER_LINE = 16

NOTICE = [
    "Weather icons derived from https://github.com/metno/weathericons,",
    "licensed under the MIT License, copyright (c) 2015-2017 Yr.",
    f"Full licence in {LICENCE_FILE}.",
]


def icon_names():
    with urllib.request.urlopen(LISTING) as response:
        listing = json.load(response)

    return sorted(
        entry["name"][: -len(".png")]
        for entry in listing
        if entry["name"].endswith(".png")
    )


def labels():
    """Map every symbol code to its condition name.

    The legend lists 41 base codes; the 21 marked as having variants expand to
    day, night and polartwilight, which is what makes up the 83 icons. The
    variant does not change the wording.
    """
    with urllib.request.urlopen(LEGEND) as response:
        rows = list(csv.DictReader(io.StringIO(response.read().decode("utf-8"))))

    out = {}

    for row in rows:
        # At least one Symbol ID upstream carries a trailing space.
        code = row["Symbol ID"].strip()
        label = row[LABEL_COLUMN].strip()

        if row["Variants"].strip() == "1":
            for variant in VARIANTS:
                out[f"{code}_{variant}"] = label
        else:
            out[code] = label

    return out


def write_table(names, names_to_labels):
    """Emit the sorted lookup table. Sorted order is what lets findSymbol
    bisect, and symbols.cpp static_asserts on it."""
    lines = ["// Generated by tools/genicons.py. Do not edit.", "//"]
    lines += [f"// {line}" for line in NOTICE]
    lines += [
        "#pragma once",
        "",
        '#include "icons/met_icons_black_24x24.h"',
        '#include "icons/met_icons_black_44x44.h"',
        '#include "icons/symbols.h"',
        "",
        "// Private to symbols.cpp. Being constexpr at namespace scope, this",
        "// has internal linkage, so every translation unit that includes it",
        "// gets its own copy of the table and its strings. Include symbols.h",
        "// and call findSymbol instead.",
        "//",
        "// Sorted by code. symbols.cpp bisects this and checks the ordering at",
        "// compile time.",
        "constexpr WeatherSymbol SYMBOL_TABLE[] = {",
    ]

    for name in sorted(names):
        lines.append(
            f'    {{"{name}",\n'
            f"     met_bitmap_black_24x24_{name},\n"
            f"     met_bitmap_black_44x44_{name},\n"
            f'     "{names_to_labels[name]}"}},'
        )

    lines += ["};", ""]

    with open(os.path.join(OUT, "symbols_table.h"), "w") as handle:
        handle.write("\n".join(lines))


def ensure_sources(names):
    os.makedirs(CACHE, exist_ok=True)
    os.makedirs(OUT, exist_ok=True)

    licence = os.path.join(OUT, LICENCE_FILE)

    if not os.path.exists(licence):
        print(f"fetching {LICENCE_FILE}")
        urllib.request.urlretrieve(LICENCE_URL, licence)

    for name in names:
        path = os.path.join(CACHE, f"{name}.png")

        if not os.path.exists(path):
            print(f"fetching {name}.png")
            urllib.request.urlretrieve(f"{RAW}/{name}.png", path)


def silhouette(name, size):
    """Pack one icon into rows of bits, a set bit meaning ink."""
    source = Image.open(os.path.join(CACHE, f"{name}.png")).convert("RGBA")
    alpha = source.split()[3].resize((size, size), RESAMPLE)

    stride = (size + 7) // 8
    packed = bytearray(stride * size)

    for y in range(size):
        for x in range(size):
            if alpha.getpixel((x, y)) >= ALPHA_CUT:
                packed[y * stride + x // 8] |= 0x80 >> (x % 8)

    return bytes(packed)


def format_bytes(packed):
    lines = []

    for start in range(0, len(packed), BYTES_PER_LINE):
        chunk = packed[start : start + BYTES_PER_LINE]
        row = ", ".join(f"0x{b:02x}" for b in chunk)
        last = start + BYTES_PER_LINE >= len(packed)

        lines.append(f"    {row}" if last else f"    {row},")

    return "\n".join(lines)


def write_set(size, names, bitmaps):
    stem = f"met_icons_black_{size}x{size}"
    prefix = f"met_bitmap_black_{size}x{size}"

    preamble = ["// Generated by tools/genicons.py. Do not edit.", "//"]
    preamble += [f"// {line}" for line in NOTICE]

    header = preamble + ["#pragma once", ""]
    header += [
        f"// Definitions live in {stem}.cpp. Declaring them extern here gives",
        "// them external linkage, so the data exists once in the final binary",
        "// instead of once per translation unit that includes it.",
        "",
    ]
    header += [f"extern const unsigned char {prefix}_{name}[];" for name in names]

    with open(os.path.join(OUT, f"{stem}.h"), "w") as handle:
        handle.write("\n".join(header) + "\n")

    body = preamble + ["// clang-format off", "", "#include <pgmspace.h>", ""]
    body += [f'#include "icons/{stem}.h"', ""]

    for name in names:
        body += [
            f"// '{name}', {size}x{size}px",
            f"const unsigned char {prefix}_{name}[] PROGMEM = {{",
            format_bytes(bitmaps[name]),
            "};",
            "",
        ]

    with open(os.path.join(OUT, f"{stem}.cpp"), "w") as handle:
        handle.write("\n".join(body))


def main():
    names = icon_names()
    ensure_sources(names)

    total = 0

    for size in SIZES:
        bitmaps = {name: silhouette(name, size) for name in names}
        write_set(size, names, bitmaps)

        stride = (size + 7) // 8
        each = stride * size
        total += len(names) * each

        print(f"{size}x{size}: {len(names)} icons, {each} B each, "
              f"{len(names) * each} B")

    names_to_labels = labels()
    missing = [n for n in names if n not in names_to_labels]

    if missing:
        raise SystemExit(f"legend has no label for: {missing}")

    write_table(names, names_to_labels)

    print(f"symbols_table.h: {len(names)} entries")
    print(f"\ntotal flash: {total} B")


if __name__ == "__main__":
    main()
