[env:lolin_d32_pro]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lolin_d32_pro
framework = arduino
build_src_flags = -Wall -Wextra
build_flags =
    -DCFG_WIFI_SSID='"${sysenv.WIFI_SSID}"'
    -DCFG_WIFI_PASSWORD='"${sysenv.WIFI_PASSWORD}"'
    -DCFG_BACKEND_HOST='"${sysenv.BACKEND_HOST}"'
    -DCFG_BACKEND_TOKEN='"${sysenv.BACKEND_TOKEN}"'
    -DCFG_DISPLAY_LOCATION='"${sysenv.DISPLAY_LOCATION}"'
    -DCFG_DISPLAY_PADDING_TOP='"${sysenv.DISPLAY_PADDING_TOP}"'
    -DCFG_DISPLAY_PADDING_RIGHT='"${sysenv.DISPLAY_PADDING_RIGHT}"'
    -DCFG_DISPLAY_PADDING_BOTTOM='"${sysenv.DISPLAY_PADDING_BOTTOM}"'
    -DCFG_DISPLAY_PADDING_LEFT='"${sysenv.DISPLAY_PADDING_LEFT}"'
lib_deps =
    adafruit/Adafruit GFX Library@1.12.6
    arduino-libraries/Arduino_JSON@0.1.0
    zinggjm/GxEPD2@1.6.9
