version: '3'

tasks:
  run-backend:
    cmds:
      - go run -race ./cmd/server
    dir: backend/
    env:
      CALENDAR_URL: "todo"
      WEATHER_URL: "https://api.met.no/weatherapi/locationforecast/2.0"
      SQLITE_PATH: "storage.db"
  build-backend:
    cmds:
      - go build -a -ldflags '-s -w' -trimpath -installsuffix cgo -o server cmd/server/main.go 
    env:
      GO111MODULE: "on"
      CGO_ENABLED: 0
    dir: backend/
  run-frontend:
    cmds:
      - npm run dev
    dir: frontend/
  build-frontend:
    cmds:
      - npm run build
    dir: frontend/
  build-esp:
    cmds:
      - pio run
    dir: esp32/
  upload-esp:
    cmds:
      - pio run --target upload
    dir: esp32/
  monitor-esp:
    cmds:
      - pio device monitor -e lolin_d32_pro -b 115200
    dir: esp32/
  help:
    desc: Display help
    silent: true
    cmds:
      - task --list

