version: '3'

tasks:
  run:
    cmds:
      - go run -race ./cmd/server
    env:
      CALENDAR_URL: "todo"
      SQLITE_PATH: "storage.db"
  help:
    desc: Display help
    silent: true
    cmds:
      - task --list

