// Generated by tools/genfonts.py. Do not edit.
#pragma once

#include <cstdint>

namespace ui {

// Codepoints above Latin-1 and the font index each is stored at.
struct GlyphMapping {
  uint32_t codepoint;
  uint8_t index;
};

constexpr GlyphMapping EXTRA_GLYPHS[] = {
    {0x2026, 0x80},  // …
    {0x2013, 0x81},  // –
    {0x2014, 0x82},  // —
    {0x2018, 0x83},  // ‘
    {0x2019, 0x84},  // ’
    {0x201C, 0x85},  // “
    {0x201D, 0x86},  // ”
    {0x2022, 0x87},  // •
    {0x20AC, 0x88},  // €
};

}  // namespace ui
