// Generated by tools/genicons.py. Do not edit.
//
// Weather icons derived from https://github.com/metno/weathericons,
// licensed under the MIT License, copyright (c) 2015-2017 Yr.
// Full licence in LICENSE-weathericons.txt.
#pragma once

// Definitions live in met_icons_black_44x44.cpp. Declaring them extern here gives
// them external linkage, so the data exists once in the final binary
// instead of once per translation unit that includes it.

extern const unsigned char met_bitmap_black_44x44_clearsky_day[];
extern const unsigned char met_bitmap_black_44x44_clearsky_night[];
extern const unsigned char met_bitmap_black_44x44_clearsky_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_cloudy[];
extern const unsigned char met_bitmap_black_44x44_fair_day[];
extern const unsigned char met_bitmap_black_44x44_fair_night[];
extern const unsigned char met_bitmap_black_44x44_fair_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_fog[];
extern const unsigned char met_bitmap_black_44x44_heavyrain[];
extern const unsigned char met_bitmap_black_44x44_heavyrainandthunder[];
extern const unsigned char met_bitmap_black_44x44_heavyrainshowers_day[];
extern const unsigned char met_bitmap_black_44x44_heavyrainshowers_night[];
extern const unsigned char met_bitmap_black_44x44_heavyrainshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_heavyrainshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_heavyrainshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_heavyrainshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_heavysleet[];
extern const unsigned char met_bitmap_black_44x44_heavysleetandthunder[];
extern const unsigned char met_bitmap_black_44x44_heavysleetshowers_day[];
extern const unsigned char met_bitmap_black_44x44_heavysleetshowers_night[];
extern const unsigned char met_bitmap_black_44x44_heavysleetshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_heavysleetshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_heavysleetshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_heavysleetshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_heavysnow[];
extern const unsigned char met_bitmap_black_44x44_heavysnowandthunder[];
extern const unsigned char met_bitmap_black_44x44_heavysnowshowers_day[];
extern const unsigned char met_bitmap_black_44x44_heavysnowshowers_night[];
extern const unsigned char met_bitmap_black_44x44_heavysnowshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_heavysnowshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_heavysnowshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_heavysnowshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_lightrain[];
extern const unsigned char met_bitmap_black_44x44_lightrainandthunder[];
extern const unsigned char met_bitmap_black_44x44_lightrainshowers_day[];
extern const unsigned char met_bitmap_black_44x44_lightrainshowers_night[];
extern const unsigned char met_bitmap_black_44x44_lightrainshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_lightrainshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_lightrainshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_lightrainshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_lightsleet[];
extern const unsigned char met_bitmap_black_44x44_lightsleetandthunder[];
extern const unsigned char met_bitmap_black_44x44_lightsleetshowers_day[];
extern const unsigned char met_bitmap_black_44x44_lightsleetshowers_night[];
extern const unsigned char met_bitmap_black_44x44_lightsleetshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_lightsnow[];
extern const unsigned char met_bitmap_black_44x44_lightsnowandthunder[];
extern const unsigned char met_bitmap_black_44x44_lightsnowshowers_day[];
extern const unsigned char met_bitmap_black_44x44_lightsnowshowers_night[];
extern const unsigned char met_bitmap_black_44x44_lightsnowshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_lightssleetshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_lightssleetshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_lightssleetshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_lightssnowshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_lightssnowshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_lightssnowshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_partlycloudy_day[];
extern const unsigned char met_bitmap_black_44x44_partlycloudy_night[];
extern const unsigned char met_bitmap_black_44x44_partlycloudy_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_rain[];
extern const unsigned char met_bitmap_black_44x44_rainandthunder[];
extern const unsigned char met_bitmap_black_44x44_rainshowers_day[];
extern const unsigned char met_bitmap_black_44x44_rainshowers_night[];
extern const unsigned char met_bitmap_black_44x44_rainshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_rainshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_rainshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_rainshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_sleet[];
extern const unsigned char met_bitmap_black_44x44_sleetandthunder[];
extern const unsigned char met_bitmap_black_44x44_sleetshowers_day[];
extern const unsigned char met_bitmap_black_44x44_sleetshowers_night[];
extern const unsigned char met_bitmap_black_44x44_sleetshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_sleetshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_sleetshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_sleetshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_snow[];
extern const unsigned char met_bitmap_black_44x44_snowandthunder[];
extern const unsigned char met_bitmap_black_44x44_snowshowers_day[];
extern const unsigned char met_bitmap_black_44x44_snowshowers_night[];
extern const unsigned char met_bitmap_black_44x44_snowshowers_polartwilight[];
extern const unsigned char met_bitmap_black_44x44_snowshowersandthunder_day[];
extern const unsigned char met_bitmap_black_44x44_snowshowersandthunder_night[];
extern const unsigned char met_bitmap_black_44x44_snowshowersandthunder_polartwilight[];
