// Generated by tools/genicons.py. Do not edit.
//
// Weather icons derived from https://github.com/metno/weathericons,
// licensed under the MIT License, copyright (c) 2015-2017 Yr.
// Full licence in LICENSE-weathericons.txt.
#pragma once

// Definitions live in met_icons_black_24x24.cpp. Declaring them extern here gives
// them external linkage, so the data exists once in the final binary
// instead of once per translation unit that includes it.

extern const unsigned char met_bitmap_black_24x24_clearsky_day[];
extern const unsigned char met_bitmap_black_24x24_clearsky_night[];
extern const unsigned char met_bitmap_black_24x24_clearsky_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_cloudy[];
extern const unsigned char met_bitmap_black_24x24_fair_day[];
extern const unsigned char met_bitmap_black_24x24_fair_night[];
extern const unsigned char met_bitmap_black_24x24_fair_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_fog[];
extern const unsigned char met_bitmap_black_24x24_heavyrain[];
extern const unsigned char met_bitmap_black_24x24_heavyrainandthunder[];
extern const unsigned char met_bitmap_black_24x24_heavyrainshowers_day[];
extern const unsigned char met_bitmap_black_24x24_heavyrainshowers_night[];
extern const unsigned char met_bitmap_black_24x24_heavyrainshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_heavyrainshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_heavyrainshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_heavyrainshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_heavysleet[];
extern const unsigned char met_bitmap_black_24x24_heavysleetandthunder[];
extern const unsigned char met_bitmap_black_24x24_heavysleetshowers_day[];
extern const unsigned char met_bitmap_black_24x24_heavysleetshowers_night[];
extern const unsigned char met_bitmap_black_24x24_heavysleetshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_heavysleetshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_heavysleetshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_heavysleetshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_heavysnow[];
extern const unsigned char met_bitmap_black_24x24_heavysnowandthunder[];
extern const unsigned char met_bitmap_black_24x24_heavysnowshowers_day[];
extern const unsigned char met_bitmap_black_24x24_heavysnowshowers_night[];
extern const unsigned char met_bitmap_black_24x24_heavysnowshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_heavysnowshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_heavysnowshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_heavysnowshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_lightrain[];
extern const unsigned char met_bitmap_black_24x24_lightrainandthunder[];
extern const unsigned char met_bitmap_black_24x24_lightrainshowers_day[];
extern const unsigned char met_bitmap_black_24x24_lightrainshowers_night[];
extern const unsigned char met_bitmap_black_24x24_lightrainshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_lightrainshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_lightrainshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_lightrainshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_lightsleet[];
extern const unsigned char met_bitmap_black_24x24_lightsleetandthunder[];
extern const unsigned char met_bitmap_black_24x24_lightsleetshowers_day[];
extern const unsigned char met_bitmap_black_24x24_lightsleetshowers_night[];
extern const unsigned char met_bitmap_black_24x24_lightsleetshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_lightsnow[];
extern const unsigned char met_bitmap_black_24x24_lightsnowandthunder[];
extern const unsigned char met_bitmap_black_24x24_lightsnowshowers_day[];
extern const unsigned char met_bitmap_black_24x24_lightsnowshowers_night[];
extern const unsigned char met_bitmap_black_24x24_lightsnowshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_lightssleetshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_lightssleetshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_lightssleetshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_lightssnowshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_lightssnowshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_lightssnowshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_partlycloudy_day[];
extern const unsigned char met_bitmap_black_24x24_partlycloudy_night[];
extern const unsigned char met_bitmap_black_24x24_partlycloudy_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_rain[];
extern const unsigned char met_bitmap_black_24x24_rainandthunder[];
extern const unsigned char met_bitmap_black_24x24_rainshowers_day[];
extern const unsigned char met_bitmap_black_24x24_rainshowers_night[];
extern const unsigned char met_bitmap_black_24x24_rainshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_rainshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_rainshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_rainshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_sleet[];
extern const unsigned char met_bitmap_black_24x24_sleetandthunder[];
extern const unsigned char met_bitmap_black_24x24_sleetshowers_day[];
extern const unsigned char met_bitmap_black_24x24_sleetshowers_night[];
extern const unsigned char met_bitmap_black_24x24_sleetshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_sleetshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_sleetshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_sleetshowersandthunder_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_snow[];
extern const unsigned char met_bitmap_black_24x24_snowandthunder[];
extern const unsigned char met_bitmap_black_24x24_snowshowers_day[];
extern const unsigned char met_bitmap_black_24x24_snowshowers_night[];
extern const unsigned char met_bitmap_black_24x24_snowshowers_polartwilight[];
extern const unsigned char met_bitmap_black_24x24_snowshowersandthunder_day[];
extern const unsigned char met_bitmap_black_24x24_snowshowersandthunder_night[];
extern const unsigned char met_bitmap_black_24x24_snowshowersandthunder_polartwilight[];
